{"name": "Неудачный логин с неверными данными", "status": "passed", "steps": [{"name": "Получение неверных данных для логина", "status": "passed", "start": 1724081809174, "stop": 1724081809174}, {"name": "Выполнение логина", "status": "passed", "start": 1724081809174, "stop": 1724081809388}, {"name": "Проверка отказа в логине", "status": "passed", "start": 1724081809388, "stop": 1724081809389}], "start": 1724081809174, "stop": 1724081809392, "uuid": "e9b18703-a9aa-4628-a2e5-eac215d89eaa", "historyId": "3cea4a21600370fdc7e3fff368f7aa45", "testCaseId": "3cea4a21600370fdc7e3fff368f7aa45", "fullName": "tests.test_user_login.TestLogin#test_login_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MacBook-Pro-w-adm-8.local"}, {"name": "thread", "value": "80051-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}